In [2]:
import pandas as pd
import numpy as np

In [4]:
# carregando o dataset
df_principal = pd.read_csv('netflix_large_dataset_cleaned.csv')
display(df_principal)
display(df_principal.describe())
display(df_principal.info())

,user_id,age_group,gender,country,region,subscription_plan,monthly_fee,subscription_start_date,subscription_end_date,payment_method,...,session_count,completion_percentage,date_watched,time_of_day,rating,liked,recommendation_source,days_since_last_watch,avg_weekly_watch_time,content_diversity_score
0,U100000,21,Female,Canada,North America,Basic,8.99,2022-03-01,2022-04-19 00:00:00,Bank Transfer,...,2,100,2022-05-23,Night,5,Yes,Trending,54,156,0.35
1,U100001,17,Female,Nigeria,Africa,Basic,8.99,2022-12-02,2026-02-07,Bank Transfer,...,1,86,2023-03-29,Evening,3,No,Trending,55,150,0.49
2,U100002,60,Male,Nigeria,Africa,Standard,13.99,2023-09-01,2026-02-07,Card,...,3,100,2023-09-15,Evening,3,No,Friend,10,245,0.28
3,U100003,60,Male,Nigeria,Africa,Standard,13.99,2024-05-26,2026-02-07,Card,...,3,100,2025-01-31,Afternoon,3,No,Trending,54,285,0.73
4,U100004,50,Female,Canada,North America,Basic,8.99,2023-12-19,2026-02-07,Bank Transfer,...,2,100,2024-06-17,Afternoon,4,Yes,Algorithm,8,139,0.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,U149995,40,Female,UK,Europe,Basic,8.99,2022-03-29,2023-05-09 00:00:00,Bank Transfer,...,1,91,2022-06-01,Night,3,No,Algorithm,25,196,0.54
49996,U149996,17,Male,USA,North America,Standard,13.99,2022-07-20,2026-02-07,Card,...,2,92,2022-12-31,Afternoon,2,No,Search,24,241,0.93
49997,U149997,17,Male,Brazil,South America,Standard,13.99,2024-06-07,2026-02-07,Card,...,3,100,2024-08-05,Night,3,No,Ads,4,272,0.58
49998,U149998,21,Female,South Africa,Africa,Premium,17.99,2023-02-05,2026-02-07,Card,...,4,100,2023-09-11,Afternoon,4,Yes,Search,38,341,0.86
49999,U149999,40,Male,Brazil,South America,Basic,8.99,2023-08-19,2026-02-07,Card,...,1,81,2024-05-30,Morning,2,No,Algorithm,17,208,0.55

,age_group,monthly_fee,release_year,watch_time_minutes,session_count,completion_percentage,rating,days_since_last_watch,avg_weekly_watch_time,content_diversity_score
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,36.412180,12.990900,2011.534020,84.999620,2.358740,91.915480,3.417980,29.938080,256.341400,0.601056
std,15.313068,3.610202,6.963695,28.086897,0.966408,11.953255,1.015861,17.621492,81.632833,0.230076
min,17.000000,8.990000,2000.000000,10.000000,1.000000,20.000000,1.000000,0.000000,33.000000,0.200000
25%,21.000000,8.990000,2006.000000,63.000000,2.000000,87.000000,3.000000,15.000000,191.000000,0.400000
50%,40.000000,13.990000,2011.000000,83.000000,2.000000,99.000000,3.000000,30.000000,251.000000,0.600000
75%,50.000000,17.990000,2018.000000,106.000000,3.000000,100.000000,4.000000,45.000000,318.250000,0.800000
max,60.000000,17.990000,2025.000000,180.000000,6.000000,100.000000,5.000000,60.000000,499.000000,1.000000

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  50000 non-null  str
 1   age_group                50000 non-null  int64
 2   gender                   50000 non-null  str
 3   country                  50000 non-null  str
 4   region                   50000 non-null  str
 5   subscription_plan        50000 non-null  str
 6   monthly_fee              50000 non-null  float64
 7   subscription_start_date  50000 non-null  str
 8   subscription_end_date    50000 non-null  str
 9   payment_method           50000 non-null  str
 10  discount_applied         50000 non-null  str
 11  churn_status             50000 non-null  str
 12  title                    50000 non-null  str
 13  content_type             50000 non-null  str
 14  genre                    50000 non-null  str
 15  language                 50000 non-null  str
 16  release_year             50000 non-null  int64
 17  device_type              50000 non-null  str
 18  watch_time_minutes       50000 non-null  int64
 19  session_count            50000 non-null  int64
 20  completion_percentage    50000 non-null  int64
 21  date_watched             50000 non-null  str
 22  time_of_day              50000 non-null  str
 23  rating                   50000 non-null  int64
 24  liked                    50000 non-null  str
 25  recommendation_source    50000 non-null  str
 26  days_since_last_watch    50000 non-null  int64
 27  avg_weekly_watch_time    50000 non-null  int64
 28  content_diversity_score  50000 non-null  float64
dtypes: float64(2), int64(8), str(19)
memory usage: 11.1 MB

None

In [ ]:
# limpeza e tratamento dos dados
df_principal = df_principal.drop_duplicates(subset=['user_id', 'subscription_start_date'])

df_principal['subscription_start_date'] = pd.to_datetime(
    df_principal['subscription_start_date'], format='%Y-%m-%d', errors='coerce'
)
df_principal['subscription_end_date'] = pd.to_datetime(
    df_principal['subscription_end_date'], format='mixed', errors='coerce'
).dt.date
df_principal['date_watched'] = pd.to_datetime(
    df_principal['date_watched'], format='%Y-%m-%d', errors='coerce'
)

colunas_texto = [
    'gender', 'country', 'region', 'subscription_plan', 'payment_method',
    'time_of_day', 'liked', 'recommendation_source'
]
df_principal[colunas_texto] = df_principal[colunas_texto].apply(lambda col: col.str.strip().str.title())

display(df_principal)

SyntaxError: invalid syntax (4268892661.py, line 22)